// Lista os Perfil Criados
GET http://localhost:3030/


###

// Cria o Perfil
POST http://localhost:3030/profile
Content-Type: application/json

{
    "name": "Fulano",
    "email": "fulano@gmail.com",
    "password": 12345
}


###

// Modifica Informações do Perfil
PUT http://localhost:3030/profile/ InsiraIdPerfil
Content-Type: application/json

{
    "name": "Beltano",
    "email": "beltano@gmail.com",
    "password": 12345
}
###

###

// Deleta o Perfil
DELETE http://localhost:3030/profile/ InsiraIdPerfil